apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=591234613960.dkr.ecr.us-east-1.amazonaws.com/nginx-test
    argocd-image-updater.argoproj.io/nginx.update-strategy: semver
    argocd-image-updater.argoproj.io/nginx.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/nginx.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/prasad-moru/GenAiStoreApp.git # Replace with your Git repo
    targetRevision: main
    path: nginx-test-chart
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true